diff --git a/Makefile.in b/Makefile.in
index bcc8457..9985a42 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -373,7 +373,7 @@ $(CURL_VERSION)/.chrome: $(chrome_libs)	$(CURL_VERSION).tar.gz $(CURL_VERSION)/.
 	  if test -n "$(with_ca_path)"; then \
 		config_flags="$$config_flags --with-ca-path=$(with_ca_path)"; \
 	  fi; \
-	  add_libs="-pthread -lc++"; \
+	  add_libs="-pthread -lstdc++"; \
 	}
 
 	echo "Configuring curl with: $$config_flags"
